# Generated by Django 2.2.6 on 2019-12-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0003_auto_20191130_2158'),
        ('Importacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacionlineaingreso',
            options={'verbose_name': 'Importacion Linea de Ingreso', 'verbose_name_plural': 'Importacion Lineas de Ingreso'},
        ),
        migrations.CreateModel(
            name='ImportacionDistribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion')),
            ],
            options={
                'verbose_name': 'Importacion de Distribucion',
                'verbose_name_plural': 'Importacion de Distribuciones',
            },
        ),
    ]
