# Generated by Django 2.2.6 on 2019-11-27 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=50)),
                ('fecha_de_creacion', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Distribucion',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
        migrations.CreateModel(
            name='DistribucionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_asignado', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Distribucion Producto',
                'verbose_name_plural': 'Distribuciones Productos',
            },
        ),
        migrations.CreateModel(
            name='EgresosPuntoDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9)),
                ('fecha_y_hora_de_egreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_y_hora_de_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-fecha_y_hora_de_registro'],
                'verbose_name': 'Egreso Punto de Recepción',
                'verbose_name_plural': 'Egreso Punto de Recepción',
            },
        ),
        migrations.CreateModel(
            name='IngresosAPuntosDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora_de_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9)),
                ('fecha_y_hora_de_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['-fecha_y_hora_de_registro'],
                'verbose_name': 'Ingresos a Punto de Recepción',
                'verbose_name_plural': 'Ingresos a Punto de Recepción',
            },
        ),
        migrations.CreateModel(
            name='LineaDeEgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Línea de Egreso de PR',
                'verbose_name_plural': 'Líneas de Egreso de PR',
            },
        ),
        migrations.CreateModel(
            name='LineaDeIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Línea de Ingreso a PR',
                'verbose_name_plural': 'Líneas de Ingreso a PR',
            },
        ),
        migrations.CreateModel(
            name='LineaDistribucionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Linea de Distribucion de Producto',
                'verbose_name_plural': 'Lineas de Distribucion de Productos',
            },
        ),
        migrations.CreateModel(
            name='LineaListaDestinosEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Linea de Destino',
                'verbose_name_plural': 'Lineas de Destino',
            },
        ),
        migrations.CreateModel(
            name='ListaDestinosEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=20)),
                ('ultima_modificacion', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lista de Destinos',
                'verbose_name_plural': 'Listas de Destinos',
            },
        ),
    ]
