# Generated by Django 2.2.6 on 2019-11-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Movimientos', '0001_initial'),
        ('Organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadestinosegreso',
            name='puntoDeRecepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='linealistadestinosegreso',
            name='listaDeDestinos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ListaDestinosEgreso'),
        ),
        migrations.AddField(
            model_name='linealistadestinosegreso',
            name='puntoDeConsumo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
        migrations.AddField(
            model_name='lineadistribucionproducto',
            name='distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.DistribucionProducto'),
        ),
        migrations.AddField(
            model_name='lineadistribucionproducto',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo', verbose_name='Punto de Consumo'),
        ),
        migrations.AddField(
            model_name='lineadeing',
            name='movimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadeing',
            name='producto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='movimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.EgresosPuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='producto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='ingreso_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='distribucion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion', verbose_name='Distribucion'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='producto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='punto_de_recepcion_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
    ]
