# Generated by Django 2.2.6 on 2019-12-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0002_auto_20191127_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadestinosegreso',
            name='puntoDeRecepcion',
        ),
        migrations.DeleteModel(
            name='LineaListaDestinosEgreso',
        ),
        migrations.DeleteModel(
            name='ListaDestinosEgreso',
        ),
    ]
