# Generated by Django 2.2.8 on 2019-12-12 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0003_auto_20191130_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresosapuntosderecepcion',
            name='distribucion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion'),
        ),
        migrations.AlterField(
            model_name='lineadeegr',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
