# Generated by Django 2.2.8 on 2019-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0005_auto_20191212_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadistribucionproducto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
