# Generated by Django 2.2.6 on 2019-11-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoGenerico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Alimento Seco', 'Alimento Seco'), ('Alimento Fresco', 'Alimento Fresco'), ('Textil', 'Textil'), ('Obras', 'Obras'), ('Otros', 'Otros')], default='', max_length=15)),
                ('tipo', models.CharField(default='', max_length=25)),
                ('unidad_de_medida', models.CharField(choices=[('Kilo', 'Kilogramos'), ('Litro', 'Litros'), ('Unidad', 'Unidad')], default='', max_length=15)),
            ],
            options={
                'verbose_name': 'Producto Genérico',
                'verbose_name_plural': 'Productos Genéricos',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(default='', max_length=40, verbose_name='Denominación del producto por parte del Proveedor')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cantidad por unidad')),
                ('pack', models.PositiveIntegerField(default=0, verbose_name='Unidades de empaque')),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.ProductoGenerico')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
            },
        ),
    ]
