# Generated by Django 2.2.6 on 2019-12-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Cantidad por unidad'),
        ),
    ]
