# Generated by Django 2.2.8 on 2019-12-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20191130_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='pack',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades de empaque'),
        ),
    ]
