# Generated by Django 2.2.8 on 2019-12-21 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizacion', '0001_initial'),
        ('Productos', '0003_auto_20191220_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=60)),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('prioridad', models.CharField(choices=[('Prioridad Alta', 'Prioridad Alta'), ('Prioridad Media', 'Prioridad Media'), ('Prioridad Baja', 'Prioridad Baja')], default='', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Menús',
                'verbose_name': 'Menú',
            },
        ),
        migrations.CreateModel(
            name='ComposicionMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menus.Menu')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.ProductoGenerico')),
            ],
            options={
                'verbose_name_plural': 'Composicion Menús',
                'verbose_name': 'Composicion Menú',
            },
        ),
        migrations.CreateModel(
            name='AsignacionMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now)),
                ('menu', models.ManyToManyField(blank=True, to='Menus.Menu')),
                ('punto_de_consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo')),
            ],
            options={
                'verbose_name_plural': 'Asignacion Menús',
                'verbose_name': 'Asignación Menú',
            },
        ),
    ]
