# Generated by Django 2.2.8 on 2019-12-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionmenu',
            name='cantidad_dias_abierto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignacionmenu',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
