# Generated by Django 2.2.8 on 2020-01-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0002_auto_20191222_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionmenu',
            options={'verbose_name': 'Asignación Menú', 'verbose_name_plural': 'Asignación Menús'},
        ),
    ]
