# Generated by Django 2.2.6 on 2019-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania_o_entidad', models.CharField(default='', max_length=50)),
                ('tipo_de_proveedor', models.CharField(choices=[('Boca Nación', 'Boca Nación'), ('Convenio Merienda', 'Convenio Merienda')], default='', max_length=20)),
                ('ubicacion', models.CharField(default='', max_length=80)),
                ('localidad', models.CharField(default='', max_length=40)),
                ('provincia', models.CharField(default='', max_length=40)),
                ('nombre_contacto', models.CharField(default='', max_length=40)),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(default='', max_length=254)),
                ('observacion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedor',
            },
        ),
    ]
